-- IT431 Project 2 — sample schema for the "products" table.
--
-- Paste this into the Supabase SQL Editor, adjust the column list to match
-- your domain (recipes, games, movies, etc.), then run it. You'll need the
-- matching Product type in src/types.ts.

create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,

  -- TODO: replace these placeholders with your real fields (at least 5).
  title        text    not null,
  artist      text    not null,
  genre    text    not null,
  release_year   integer check (release_year > 1990),
  track_count      integer check (track_count > 0),
  label    text
);

-- Row Level Security: the database, not the UI, decides who can do what.
alter table public.albums enable row level security;

-- Anyone (including anonymous visitors) can read.
create policy "albums_select_anyone"
  on public.albums for select
  using (true);

-- Only signed-in users can insert, and they must stamp their own user_id.
create policy "albums_insert_authenticated"
  on public.albums for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Users can only edit rows they created.
create policy "albums_update_owner"
  on public.albums for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Users can only delete rows they created.
create policy "albums_delete_owner"
  on public.albums for delete
  to authenticated
  using (auth.uid() = user_id);
